### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by manzilzaheer** [mirefek/py_euclidea#1]
Hello,

Thanks for making this really cool environment.

Can you please add a license of your choice to this repository? It would allow me and many others to play with code in confidence.

Thanks!

**Comment by mirefek** [comment]
As of me, I would be happy to be benevolent about licensing. However, I am not associated with the original Euclidea game, and I prefer asking the author of the original game as I rewritten the original levels really closely. If I don't get a response from them, I will just add a license of my choice.

**Comment by manzilzaheer** [comment]
Thanks. I appreciate your efforts :)

**Comment by cmdowney** [comment]
+1. Thanks this would be super helpful :).

**Comment by shehzaadzd** [comment]
Agree, that would be super useful, thanks! :)

**Comment by mirefek** [comment]
[Enjoy!](https://github.com/mirefek/py_euclidea/blob/master/LICENSE.md)
